---
- hosts: local
  become: true
  tasks: 
    - name: Install required components
      apt:
        name: 
          - git
          - maven
          - openjdk-17-jdk
        state: present
    - name: Clone Maven repo
      git:
        repo: https://github.com/Prematvasudev/FST_JUnit_Project.git
        dest: /home/Prematvasudev/FST_Training
    
    - name: Run Maven tests
      command: mvn clean test
      args:
        chdir: /home/Prematvasudev/FST_Training

